# Generated by Django 3.1.2 on 2021-01-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210102_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Avobe to Read BLog Post', max_length=255),
        ),
    ]
