# Generated by Django 3.1.2 on 2021-01-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above to Read BLog Post', max_length=255),
        ),
    ]
